apiVersion: v1
kind: Service
metadata:
  name: xdata-web-svc
  namespace: default
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: xdata-web
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xdata-web
  name: xdata-web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xdata-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: xdata-web
    spec:
      containers:
        - env:
            - name: PKG_RELEASE
              value: 1~buster
          image: 086115989834.dkr.ecr.cn-northwest-1.amazonaws.com.cn/ijingzhun/xdata-web:0.0.85
          imagePullPolicy: IfNotPresent
          name: xdata-web
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
          